#:schema https://mise.jdx.dev/schema/mise.json

[tools]
bun = "latest"
go = "latest"
node = "24"
ruby = "latest"
usage = "latest"
zig = "latest"

[settings]
disable_hints = ["outdated_bump"]
idiomatic_version_file_enable_tools = ["node", "ruby"]
