# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  showBottomLine: false
  showCommandLog: false
  showFileTree: false
  showIcons: true
  theme:
    selectedLineBgColor:
      - '#383838'
    # selectedRangeBgColor:
    #   - '#383838'  # Bug: https://github.com/jesseduffield/lazygit/issues/1749
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --true-color=auto --diff-so-fancy
notARepository: 'quit'
promptToReturnFromSubprocess: false
keybinding:
  universal:
    return: 'q'
    prevBlock-alt: '<c-k>'
    nextBlock-alt: '<c-j>'
    nextTab: 'l'
    prevTab: 'h'
    prevScreenMode: '-'
    startSearch: 'Ã±'
  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'
