# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  nerdFontsVersion: 3
  showBottomLine: false
  showCommandLog: false
  showFileTree: false
  skipRewordInEditorWarning: true
  theme:
    selectedLineBgColor:
      - '#262626'
    selectedRangeBgColor:
      - black
      - bold
git:
  log:
    showGraph: always
  paging:
    colorArg: always
    pager: delta --paging=never --tabs=2
  parseEmoji: true
notARepository: 'quit'
promptToReturnFromSubprocess: false
keybinding:
  universal:
    return: 'q'
    prevBlock-alt: '<c-k>'
    nextBlock-alt: '<c-j>'
    nextTab: 'l'
    prevTab: 'h'
    prevScreenMode: '-'
    startSearch: 'Ã±'
  commits:
    moveDownCommit: 'J'
    moveUpCommit: 'K'
  files:
    commitChanges: 'C'
    commitChangesWithEditor: 'c'
