#:schema https://raw.githubusercontent.com/openai/codex/refs/heads/main/codex-rs/core/config.schema.json

web_search = "live"

[sandbox_workspace_write]
network_access = true

[shell_environment_policy]
ignore_default_excludes = true  # inherit all env variables
