[tui]
# Examples: true | ["agent-turn-complete", "approval-requested"]
notifications = true
notify = ["notify-send", "Codex"]

[features]
web_search_request = true

[shell_environment_policy]
ignore_default_excludes = true  # inherit all env variables
